architecture:
  name: pyannote.audio.models.PyanNet
  params:
    ff:
      hidden_size:
      - 128
      - 128
    rnn:
      bidirectional: true
      hidden_size: 128
      num_layers: 2
      unit: LSTM
data_augmentation:
  name: AddNoise
  params:
    collection: MUSAN.Collection.BackgroundNoise
    snr_max: 20
    snr_min: 5
feature_extraction:
  name: RawAudio
  params:
    sample_rate: 16000
scheduler:
  name: ConstantScheduler
  params:
    learning_rate: 0.01
task:
  name: SpeakerChangeDetection
  params:
    batch_size: 64
    duration: 2.0
    per_epoch: 1
