architecture:
  name: pyannote.audio.models.PyanNet
  params:
    embedding:
      batch_normalize: false
      unit_normalize: false
    ff:
      hidden_size:
      - 128
      - 128
    rnn:
      bidirectional: true
      hidden_size: 128
      num_layers: 2
      unit: LSTM
    sincnet:
      instance_normalize: true
      stride:
      - 5
      - 1
      - 1
      waveform_normalize: true
    tdnn:
      embedding_dim: 512
feature_extraction:
  name: RawAudio
  params:
    sample_rate: 16000
scheduler:
  name: ConstantScheduler
  params:
    learning_rate: 0.01
task:
  name: SpeakerChangeDetection
  params:
    batch_size: 64
    collar: 0.1
    duration: 2.0
    label_min_duration: 30
    margin: 0.05
    non_speech: false
    per_fold: 128
    per_label: 1
    per_turn: 1
    s: 10
